"""Configuration for the unmask local diffusion server."""

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
LLAMA_CPP_DIR = PROJECT_ROOT / "llama.cpp"

CLI_PATH = str(LLAMA_CPP_DIR / "build/bin/llama-diffusion-cli")
DIFFUSION_SERVER_PATH = str(LLAMA_CPP_DIR / "build/bin/llama-diffusion-server")
MODELS_DIR = "~/unmask/models"

DEFAULT_STEPS = 128
DEFAULT_TOKENS = 512
DEFAULT_TEMP = 0.2

HOST = "0.0.0.0"
PORT = 11434
GPU_LAYERS = "99"
CLI_TIMEOUT_SECONDS = 120

USE_PERSISTENT_WORKER = True
FALLBACK_TO_CLI = True
DIFFUSION_WORKER_HOST = "127.0.0.1"
DIFFUSION_WORKER_PORT = 8088
DIFFUSION_WORKER_URL = f"http://{DIFFUSION_WORKER_HOST}:{DIFFUSION_WORKER_PORT}"
WORKER_MAX_SEQUENCE_LENGTH = 1024
WORKER_STARTUP_TIMEOUT_SECONDS = 180
WORKER_REQUEST_TIMEOUT_SECONDS = 300
